### PR TITLE
Search improvements vol. 2 + minor fixes

### LINKED ISSUE #69: param languages is empty, breaks the searching
According the log I can see not very often, but sometimes we get query like this:

```
https://api.opensubtitles.com/api/v1/subtitles?episode_number=1&languages=moviehash=5716a7688381082d&moviehash_match=only&query=marvel%27s+the+punisher&season_number=1&type=episode
```

as you can see, languages is empty, so it won't return anything. Please check the code, if this can happen at your side

### LINKED ISSUE #73: Error downloading subtitles from "Open Subtitles"
An error occurred when I used OpenSubtitles to download
version：10.7.7
os：Linux X64

`[2021-11-01 02:37:36.369 +00:00] [ERR] [42] MediaBrowser.Providers.Subtitles.SubtitleManager: Error downloading subtitles from "Open Subtitles"
System.Text.Json.JsonException: Failed to parse response, code: Moved, context: options: System.Collections.Generic.Dictionary`2[System.String,System.String], page: 1, body: 
""
 ---> System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   at OpenSubtitlesHandler.Models.ApiResponse`1..ctor(HttpResponse response, String[] context)
   --- End of inner exception stack trace ---
   at OpenSubtitlesHandler.Models.ApiResponse`1..ctor(HttpResponse response, String[] context)
   at OpenSubtitlesHandler.OpenSubtitles.SearchSubtitlesAsync(Dictionary`2 options, String apiKey, CancellationToken cancellationToken)
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.SearchSubtitles(SubtitleSearchRequest request, CancellationToken cancellationToken)`

### PR DESCRIPTION
**Pull request by MBR-0001**
Part 1/2 of changes suggested/requested by OpenSubtitles

Changes:
- Search params are all lowercase & properly sorted alphabetically
- Query is (again) provided only when imdb id is missing
- 3xx status codes are not considered valid anymore (fixes #73)
- [Weird string trickery](https://github.com/jellyfin/jellyfin-plugin-opensubtitles/commit/b8337449a5143684528de455fb498cd6d72e4ff6) is replaced by the new `reset_time_utc` property  

Closes #69

### CODE REVIEW

File: OpenSubtitlesHandler/OpenSubtitles.cs [hunk 1]
```diff
@@ -15,6 +15,8 @@ namespace OpenSubtitlesHandler
     /// </summary>
     public static class OpenSubtitles
     {
+        private static readonly CultureInfo _usCulture = CultureInfo.ReadOnly(new CultureInfo("en-US"));
```
Comment (crobibero) [inline OpenSubtitlesHandler/OpenSubtitles.cs:18]: We're trying to move away from specific cultures. As far as I know Invariant is basically `en-US`, so this can go away

Comment (MBR-0001) [reply OpenSubtitlesHandler/OpenSubtitles.cs]: Removed in ea3ebeb834ef7b86e31405f08b6237211f6c12e6

**Review by crobibero — APPROVED** [review]
